[project]
name = "argendata-datasets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "joangq", email = "jgquiroga@dc.uba.ar" }
]
requires-python = ">=3.13"
dependencies = [
    "argendata-internal-client@git+https://github.com/joangq/argendata_internal_client",
    "pydantic>=2.12.5",
]

[project.scripts]
argendata-datasets = "argendata_datasets:main"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

# [tool.uv.sources]
# argendata-internal-client = { path = "../argendata_internal_client", editable = true }
